
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LeadsProvider } from "@/contexts/LeadsContext"
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full  antialiased`}
    >
      <body className="min-h-full flex flex-col dark:bg-black">
        <LeadsProvider>
          <main className="min-h-full w-full flex flex-col dark:bg-black">
            {children}
          </main>
        </LeadsProvider>
        <Toaster />
      </body>
    </html>
  );
}
